-- Add sales_amount column to reels table for manual sales tracking
ALTER TABLE reels ADD COLUMN IF NOT EXISTS sales_amount decimal(10,2) DEFAULT NULL;

COMMENT ON COLUMN reels.sales_amount IS 'Manually entered sales amount in USD generated by this reel';
